### ISSUE TITLE
ICMP firewall rules always modified

### ISSUE THREAD

**Issue by dcarley** [gds-operations/vcloud-edge_gateway#117]
When deploying a firewall ruleset that has two ICMP rules the following changes are always recorded, meaning that the deploy isn't idempotent and we submit unnecessary changes:

```
I, [2014-12-15T10:48:05.108600 #10137]  INFO -- : Updating EdgeGateway d627d7c2-8e48-438e-9f77-98a7fb164ee9
- FirewallService.FirewallRule[39].IcmpSubType: any
- FirewallService.FirewallRule[63].IcmpSubType: any
```

**Comment by surminus** [comment]
I believe this may happen because the rules move position when they are configured (though I don't have any actual proof :neutral_face: ). I might see if it could be fixed by specifically ordering the ICMP rules at the top of the rule which I think can be specified using the rule `Id` as per https://github.com/fog/fog/blob/master/lib/fog/vcloud_director/generators/compute/edge_gateway_service_configuration.rb#L214

Requires some investigation.

**Comment by deanwilson** [comment]
This tool is no longer in active use and the repository will be archived so we're closing this issue. Thank you for your interest and involvement in this project.
